use_frameworks!

platform :ios, '8.0'

target 'Categorys_Example' do
  pod 'Categorys', :path => '../'

  target 'Categorys_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
